export const INCREMENT_STARTING_COUNT = 'INCREMENT_STARTING_COUNT';
export type INCREMENT_STARTING_COUNT = typeof INCREMENT_STARTING_COUNT;


export const DECREMENT_STARTING_COUNT = 'DECREMENT_STARTING_COUNT';
export type DECREMENT_STARTING_COUNT = typeof DECREMENT_STARTING_COUNT;